# Generated by Django 3.2.8 on 2022-04-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEquipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='carrera',
            field=models.CharField(max_length=6, verbose_name='Carrera(4 digitos)'),
        ),
    ]
